Feat/layered maps
Iconica-Development/flutter_locations pull request #3
Opened 2024-10-02 14:49 UTC by Quirille

Small start with regards to the form builder and the maps widget.

2024-10-03 06:56 UTC, Mino03947 commented on packages/flutter_locations/.flutter-plugins-dependencies
Shouldn't this be in the .gitignore?

2024-10-03 06:57 UTC, Mino03947 commented on packages/flutter_locations/.flutter-plugins
And this in the .gitignore?

2024-10-03 06:59 UTC, Mino03947 commented on apps/example/.metadata
And this in the .gitignore?

2024-10-03 09:24 UTC, Mino03947 submitted a review, later dismissed

2024-10-03 11:02 UTC, FlutterJoey requested changes

2024-10-03 11:02 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/ui/widgets/location_maps.dart
> +final cacheProvider = FutureProvider<HiveCacheStore>((ref) async {
we should not use riverpod within a user-story, as not all apps that use this might want to depend on riverpod

2024-10-04 08:11 UTC, FlutterJoey submitted a review, later dismissed

2024-10-04 08:11 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/ui/widgets/location_maps.dart
> +    return Container();
Never return a container for an empty widget, use a SizedBox.shrink instead

2024-10-04 08:11 UTC, FlutterJoey approved these changes, later dismissed

2024-10-04 08:28 UTC, Mino03947 requested changes
Remove unused location options.

2024-10-04 09:18 UTC, FlutterJoey approved these changes

2024-10-04 09:18 UTC, Mino03947 approved these changes

2024-10-04 09:20 UTC, merged