feat: add configuration for the map
Iconica-Development/flutter_locations pull request #4
Opened 2024-10-03 09:22 UTC by Mino03947

2024-10-03 09:57 UTC, FlutterJoey requested changes

2024-10-03 09:57 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/config/flutter_locations_config.dart
You should not add options without having a use-case for them. All additions should be supported by their usage in the component. For example, the mapLayoutBuilder should be used somewhere in the build method of the map screen.

On top, I think that options should have a proper reasoning to its existence. For example, the tileserver builder is not needed as we use native implementations that do not require us to go as low as the tileserver.

2024-10-03 11:40 UTC, Mino03947 commented on packages/flutter_locations/lib/src/config/flutter_locations_config.dart
So the builder options arent needed? Done. Could you elaborate a bit more about those other points.

2024-10-04 07:02 UTC, FlutterJoey requested changes

2024-10-04 07:02 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/config/flutter_locations_config.dart
> +class FlutterLocationsConfig {
this should be called PlatformMapConfiguration. Also, make sure that whenever these options are defined, that they are also used within the component. If we simply define config but never apply them to either, we create "dead" configuration.

2024-10-04 11:51 UTC, Mino03947 commented on packages/flutter_locations/lib/src/ui/widgets/map.dart
> +    // TODO: config.poiListStyle is not used and can only be used directly in component GoogleMap.style, controller setMapStyle is deprecated.
This would mean that we need to go around platform_maps_flutter.

2024-10-04 11:57 UTC, Mino03947 commented on packages/flutter_locations/lib/src/ui/widgets/map.dart
> +                    TileLayer(
its not possible to add the poi styling to openstreetmap. This needs to be done differently if these functionalities need to be included.

2024-10-04 12:08 UTC, Mino03947 commented on packages/flutter_locations/lib/src/config/flutter_locations_config.dart
> +  final bool isScaleShown; //
Not supported by platform_maps_flutter. This could be implemented ourselves.

2024-10-04 12:36 UTC, FlutterJoey requested changes

2024-10-04 12:36 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/ui/widgets/map.dart
> +            switch (config.mapType) {
use a switch expression

2024-10-04 12:36 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/ui/widgets/map.dart
> +              initialLocation.latitude,
pretty sure this needs to be a longitude

2024-10-04 12:36 UTC, FlutterJoey commented on packages/flutter_locations/lib/src/ui/widgets/map.dart
> +                  if (config.isFallbackMapType)
the config should only be limited to the platform maps, and not be used outside. If it has global impact on the user-story it should be part of the options

2025-04-15 07:15 UTC, closed without merging